import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'adapters/jwt': 'src/adapters/jwt.ts',
    'adapters/cookie': 'src/adapters/cookie.ts',
    'adapters/session': 'src/adapters/session.ts',
    'methods/password': 'src/methods/password.ts',
    'methods/mock': 'src/methods/mock.ts',
    'methods/oauth-github': 'src/methods/oauth-github.ts',
    'methods/oauth-google': 'src/methods/oauth-google.ts',
    'methods/oauth-wechat': 'src/methods/oauth-wechat.ts',
    'methods/passkey': 'src/methods/passkey.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  minify: false,
  treeshake: true,
  external: [
    'react',
    '@swr-login/core',
    '@swr-login/react',
    '@swr-login/adapter-jwt',
    '@swr-login/adapter-cookie',
    '@swr-login/adapter-session',
    '@swr-login/method-password',
    '@swr-login/method-mock',
    '@swr-login/method-oauth-github',
    '@swr-login/method-oauth-google',
    '@swr-login/method-oauth-wechat',
    '@swr-login/method-passkey',
  ],
});
